# Generated by Django 6.0.6 on 2026-07-30 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_appointment_symptoms_patient_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('doctor_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medicine_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('test_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patient')),
            ],
        ),
    ]
