# Generated by Django 6.0.6 on 2026-08-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_laboratory'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Out of Stock', 'Out of Stock'), ('Expired', 'Expired')], default='Available', max_length=20),
        ),
    ]
