# Generated by Django 6.0.6 on 2026-08-02 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_medicine_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date', '-appointment_time']},
        ),
        migrations.AlterModelOptions(
            name='billing',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='laboratory',
            options={'ordering': ['-test_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['medicine_name']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='management.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='management.patient'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='management.doctor'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='management.patient'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_tests', to='management.patient'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='test_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='test_result',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
