# Generated by Django 6.0.6 on 2026-08-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_doctor_options_doctor_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Pending', 'Completed'])), fields=('doctor', 'appointment_date', 'appointment_time'), name='unique_active_doctor_slot'),
        ),
    ]
